name: tool_mobile
description: Flutter Tools' base plus mobile. Use to create command line tools.
version: 1.9.5+1
homepage: https://github.com/mmcc007/tool_mobile

publish_to: 'none'

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  tool_base:
    git: https://github.com/felixgabler/tool_base.git

dev_dependencies:
  mockito: ^5.4.5
  pedantic: ^1.11.1
  test: ^1.25.14
